from __future__ import annotations

from datetime import datetime, timezone
from html import escape
from typing import Any, Dict, List

from src.shared.schemas.research_state import ResearchState
from src.components.part_4_formatter.tools import save_report_file


def _current_timestamp() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _normalize_text(value: Any) -> str:
    if isinstance(value, str):
        return value.strip()
    if value is None:
        return ""
    return str(value).strip()


def _build_markdown_report(
    topic: str,
    summary: List[str],
    verified_claims: List[Dict[str, Any]],
    rejected_claims: List[Dict[str, Any]],
    sources: List[str],
    generated_on: str,
) -> str:
    lines: List[str] = [f"# Research Brief: {topic}", "", f"Generated on: {generated_on}", "", "## Executive Summary", ""]

    for item in summary:
        lines.append(f"- {item}")
    if not summary:
        lines.append("- No summary items available.")

    lines.extend(["", "## Verified Claims", ""])
    if verified_claims:
        for index, claim in enumerate(verified_claims, start=1):
            claim_text = _normalize_text(claim.get("claim") or claim.get("text") or "Unknown claim")
            source = _normalize_text(claim.get("source") or claim.get("source_url") or claim.get("source_name") or "Unknown source")
            confidence = _normalize_text(claim.get("confidence") or claim.get("confidence_score") or "N/A")
            lines.append(f"{index}. {claim_text}")
            lines.append(f"   - Source: {source}")
            lines.append(f"   - Confidence: {confidence}")
    else:
        lines.append("No verified claims were provided.")

    lines.extend(["", "## Rejected or Unverified Claims", ""])
    if rejected_claims:
        for index, claim in enumerate(rejected_claims, start=1):
            claim_text = _normalize_text(claim.get("claim") or claim.get("text") or "Unknown claim")
            reason = _normalize_text(claim.get("reason") or claim.get("rejection_reason") or "No reason provided.")
            lines.append(f"{index}. {claim_text}")
            lines.append(f"   - Reason: {reason}")
    else:
        lines.append("No rejected or unverified claims were provided.")

    lines.extend(["", "## Sources", ""])
    if sources:
        for source in sources:
            lines.append(f"- {source}")
    else:
        lines.append("- No sources were provided.")

    lines.extend([
        "",
        "## System Note",
        "This report was generated by a local multi-agent research system. Only verified information from the shared state was included.",
    ])
    return "\n".join(lines)


def _build_html_report(
    topic: str,
    summary: List[str],
    verified_claims: List[Dict[str, Any]],
    rejected_claims: List[Dict[str, Any]],
    sources: List[str],
    generated_on: str,
) -> str:
    safe_topic = escape(topic)
    safe_summary = [escape(item) for item in summary]
    safe_sources = [escape(item) for item in sources]

    verified_items: List[str] = []
    for claim in verified_claims:
        claim_text = escape(_normalize_text(claim.get("claim") or claim.get("text") or "Unknown claim"))
        source = escape(_normalize_text(claim.get("source") or claim.get("source_url") or claim.get("source_name") or "Unknown source"))
        confidence = escape(_normalize_text(claim.get("confidence") or claim.get("confidence_score") or "N/A"))
        verified_items.append(
            f"<li><strong>{claim_text}</strong><ul>"
            f"<li>Source: {source}</li>"
            f"<li>Confidence: {confidence}</li>"
            f"</ul></li>"
        )

    rejected_items: List[str] = []
    for claim in rejected_claims:
        claim_text = escape(_normalize_text(claim.get("claim") or claim.get("text") or "Unknown claim"))
        reason = escape(_normalize_text(claim.get("reason") or claim.get("rejection_reason") or "No reason provided."))
        rejected_items.append(
            f"<li><strong>{claim_text}</strong><ul><li>Reason: {reason}</li></ul></li>"
        )

    html_content = [
        "<!DOCTYPE html>",
        "<html lang=\"en\">",
        "<head>",
        "<meta charset=\"UTF-8\">",
        f"<title>Research Brief: {safe_topic}</title>",
        "<style>",
        "body { font-family: Arial, sans-serif; margin: 24px; line-height: 1.6; color: #222; }",
        "h1, h2 { color: #0b3d91; }",
        "ul { margin-left: 1.2em; }",
        "li { margin-bottom: 0.6em; }",
        "section { margin-bottom: 24px; }",
        "</style>",
        "</head>",
        "<body>",
        f"<h1>Research Brief: {safe_topic}</h1>",
        f"<p><strong>Generated on:</strong> {escape(generated_on)}</p>",
        "<section>",
        "<h2>Executive Summary</h2>",
        "<ul>",
    ]

    if safe_summary:
        html_content.extend(f"<li>{item}</li>" for item in safe_summary)
    else:
        html_content.append("<li>No summary items available.</li>")

    html_content.extend(["</ul>", "</section>", "<section>", "<h2>Verified Claims</h2>"])
    if verified_items:
        html_content.append("<ul>")
        html_content.extend(verified_items)
        html_content.append("</ul>")
    else:
        html_content.append("<p>No verified claims were provided.</p>")

    html_content.extend(["</section>", "<section>", "<h2>Rejected or Unverified Claims</h2>"])
    if rejected_items:
        html_content.append("<ul>")
        html_content.extend(rejected_items)
        html_content.append("</ul>")
    else:
        html_content.append("<p>No rejected or unverified claims were provided.</p>")

    html_content.extend(["</section>", "<section>", "<h2>Sources</h2>", "<ul>"])
    if safe_sources:
        html_content.extend(f"<li>{source}</li>" for source in safe_sources)
    else:
        html_content.append("<li>No sources were provided.</li>")

    html_content.extend([
        "</ul>",
        "</section>",
        "<section>",
        "<h2>System Note</h2>",
        "<p>This report was generated by a local multi-agent research system. Only verified information from the shared state was included.</p>",
        "</section>",
        "</body>",
        "</html>",
    ])
    return "\n".join(html_content)


def formatter_agent_node(state: ResearchState) -> ResearchState:
    """Generate a formatted research report from shared research state."""
    current_timestamp = _current_timestamp()
    output_format = (state.get("output_format") or "md").strip().lower()
    if output_format not in ("md", "html"):
        output_format = "md"

    topic = _normalize_text(state.get("topic"))
    summary = [item.strip() for item in state.get("summary", []) if isinstance(item, str) and item.strip()]
    verified_claims = state.get("verified_claims", []) or []
    rejected_claims = state.get("rejected_claims", []) or []
    sources = [item.strip() for item in state.get("sources", []) if isinstance(item, str) and item.strip()]
    log_entry: Dict[str, Any] = {
        "agent": "FormatterAgent",
        "action": "format_and_save_report",
        "status": "failed",
        "input_summary_count": len(summary),
        "verified_claim_count": len(verified_claims),
        "rejected_claim_count": len(rejected_claims),
        "source_count": len(sources),
        "output_format": output_format,
        "output_file_path": None,
        "timestamp": current_timestamp,
    }

    if not topic:
        error_message = "Missing or empty topic in research state."
        log_entry["error"] = error_message
        new_state = dict(state)
        new_state["logs"] = list(state.get("logs", [])) + [log_entry]
        raise ValueError(error_message)

    if not summary:
        error_message = "Research summary must contain at least one item."
        log_entry["error"] = error_message
        new_state = dict(state)
        new_state["logs"] = list(state.get("logs", [])) + [log_entry]
        raise ValueError(error_message)

    if output_format == "html":
        report_content = _build_html_report(topic, summary, verified_claims, rejected_claims, sources, current_timestamp)
    else:
        report_content = _build_markdown_report(topic, summary, verified_claims, rejected_claims, sources, current_timestamp)

    output_filename = f"research-report-{topic}"
    saved_path = save_report_file(report_content, output_filename, file_type=output_format, output_dir="outputs/reports")

    log_entry["status"] = "success"
    log_entry["output_file_path"] = saved_path

    new_state = dict(state)
    new_state["output_file_path"] = saved_path
    new_state["logs"] = list(state.get("logs", [])) + [log_entry]
    return new_state